
export const SET_CURRENT_COLOR = 'SET_CURRENT_COLOR'

export const SET_CURRENT_PALETTE = 'SET_CURRENT_PALETTE'

export const FETCH_PIXS = 'FETCH_PIXS'

export const FETCH_OWN_PIXS = 'FETCH_OWN_PIXS'

export const SET_SELECTED_PIX = 'SET_SELECTED_PIX'

export const LOADING_PIXS = 'LOADING_PIX'

export const SET_SAVED_DRAFT = 'SET_SAVED_DRAFT'

export const FETCH_ROOMS = 'FETCH_ROOMS' 

export const FETCH_OWN_ROOMS = 'FETCH_OWN_ROOMS'

export const SET_CURRENT_ROOM = 'SET_CURRENT_ROOM'

export const FETCH_PENDING_STUDENT_USERS = 'FETCH_PENDING_STUDENT_USERS'

export const SET_STATES = 'SET_STATES'

export const SET_SCHOOL_ROOMS_LIST = 'SET_SCHOOL_ROOMS_LIST'

export const ROOM_SIGNIN_ERROR = 'ROOM_SIGNIN_ERROR'

export const SET_BOARDVIEWS = 'SET_BOARDVIEWS'

export const FETCH_POSTS = 'FETCH_POSTS'

export const FETCH_OWN_POSTS = 'FETCH_OWN_POSTS'

export const SET_SELECTED_POST = 'SET_SELECTED_POST'

export const LOADING_POSTS = 'LOADING_POST'
